import Image from "next/image";
import Head from "next/head";
import {Container, Navbar} from "react-bootstrap";
import {ReactElement} from "react";
import Link from "next/link";
import {GitHub, Youtube} from "react-feather";

/**
 *
 * @param children
 * @constructor
 */

interface LayoutProps {
    children: ReactElement;
}
export const Layout = (props: LayoutProps) => {
    return <div>
        <Navbar bg="light" variant="light" style={{borderBottom: '1px solid gainsboro', }}>
            <Container>
                <Navbar.Brand href="#home">
                    <Image
                        className="navbar-brand mb-0 p-0 h1"
                        src="/web-logo.png"
                        alt="Picture of the web"
                        style={{border: '1px solid gray', objectFit: 'cover', borderRadius: 8}}
                        width={140}
                        height={90}
                    />
                    <Navbar.Text>
                        <h3 className={'text-black fw-bolder d-inline-block d-sm-inline-block d-none'}>Documentations</h3>
                    </Navbar.Text>
                </Navbar.Brand>
                <Navbar.Toggle />
                <Navbar.Collapse className="justify-content-end ">
                    <Navbar.Text>
                        <div className={'d-flex gap-3'}>
                            <Link href={'https://www.youtube.com/@KawinSirikhanarat'}><Youtube size={40}></Youtube></Link>
                            <Link className={'ms-2'} href={'https://github.com/gwingwin-cc'}><GitHub size={36}></GitHub></Link>
                        </div>
                    </Navbar.Text>
                </Navbar.Collapse>

            </Container>
        </Navbar>
        <Head>
            <title>Documents</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>

        <main >
            {props.children}
        </main>
    </div>
}